import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import Navigation from '@/components/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Braindie',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'relative min-h-screen pb-20')}>
        <header className="sticky top-0 bg-white/90 p-4 shadow backdrop-blur">
          <div className="mx-auto flex max-w-6xl items-center">
            <Link href="/" className="mr-12 text-lg font-bold">
              Braindie
            </Link>
            <Navigation />
          </div>
        </header>
        {props.children}
        <footer className="absolute bottom-0 flex w-full items-center justify-between border-t border-gray-500 p-4">
          <span className="font-medium">GitHub</span>
          <span>&copy; Henry Dang 2023</span>
        </footer>
        {props.modal}
      </body>
    </html>
  )
}
